{
 "title": "Store Trigger",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jobs_duration_seconds_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{service_name=\"store-trigger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{service_name=\"store-trigger\"}[3m])*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total POST Requests",
   "type": "stat",
   "description": "Represents request for creating a new model",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{service_name=\"store-trigger\", method=\"POST\"})",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "http_request_duration_seconds_count{service_name=\"store-trigger\", method=\"POST\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Average Job Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_duration_seconds_sum/jobs_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service_name=\"store-trigger\"}[2m])) by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}