name: Build and push artifacts

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
env:
  HELM_EXPERIMENTAL_OCI: 1

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_push_docker:
      uses: MapColonies/shared-workflows/.github/workflows/build-and-push-docker.yaml@feat/MAPCO-4702-image-updater
      secrets: inherit
      with:
        scope: 3d

  build_and_push_helm:
      uses: MapColonies/shared-workflows/.github/workflows/build-and-push-helm.yaml@feat/MAPCO-4702-image-updater
      secrets: inherit
      with:
        scope: 3d

  update_versions:
      uses: MapColonies/shared-workflows/.github/workflows/ci-version-updater.yaml@feat/MAPCO-4702-image-updater
      secrets: inherit
      needs: [build_and_push_docker, build_and_push_helm]
      with:
        scope: 3d
